In [79]:
import seaborn as sns
import os
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [80]:
iris = load_iris()
X = iris.data
y = iris.target

print(f"X shape : {X.shape}")
print(f"Y unique : {np.unique(y)}")
print(f"Features : {iris.feature_names}")
print(f"classes : {iris.target_names}")

X shape : (150, 4)
Y unique : [0 1 2]
Features : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
classes : ['setosa' 'versicolor' 'virginica']


# Model KNN

In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"entrainement : {X_train.shape[0]} exemple - test {X_test.shape[0]} exemple")

entrainement : 120 exemple - test 30 exemple


## Entrainement

In [82]:
# Création du modèle
knn = KNeighborsClassifier(n_neighbors=3)

# Entraînement
knn.fit(X_train, y_train)

# Prédictions
y_pred = knn.predict(X_test)

# Évaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy : {accuracy:.2f}")

Accuracy : 1.00


## F1-score

In [83]:
f1_macro = f1_score(y_test, y_pred, average="macro")

print(f"F1-score macro : {f1_macro:.4f}")

F1-score macro : 1.0000


## Matrice de confusion 3*3

In [84]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## cross-validation

In [85]:
knn_scores = cross_val_score(
    knn,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

_scores = cross_val_score(
    knn,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

print("Scores de chaque fold :", knn_scores)
print("Moyenne :", knn_scores.mean())
print("Écart-type :", knn_scores.std())

Scores de chaque fold : [0.96658312 0.96658312 0.93265993 0.96658312 1.        ]
Moyenne : 0.9664818612187034
Écart-type : 0.021295160208553578


# arbre de cécision

In [86]:
clf = DecisionTreeClassifier(
    random_state=42
)

## entrainement

In [87]:
clf.fit(X_train, y_train)

# Prédictions
y_pred = clf.predict(X_test)

# Évaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy : {accuracy:.2f}")

Accuracy : 1.00


## F1-score

In [88]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred, average="macro")

print("F1 macro :", f1)

F1 macro : 1.0


## Matrice de confusion

In [89]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Cross-validation

In [90]:
clf_score = cross_val_score(
    knn,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

_scores = cross_val_score(
    knn,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

print("Scores de chaque fold :", clf_score)
print("Moyenne :", clf_score.mean())
print("Écart-type :", clf_score.std())

Scores de chaque fold : [0.96658312 0.96658312 0.93265993 0.96658312 1.        ]
Moyenne : 0.9664818612187034
Écart-type : 0.021295160208553578


# Random forest

In [91]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

## entrainement

In [92]:
rf.fit(X_train, y_train)

# Prédictions
y_pred = rf.predict(X_test)

# Évaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy : {accuracy:.2f}")

Accuracy : 1.00


## F1-score

In [93]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred, average="macro")

print("F1 macro :", f1)

F1 macro : 1.0


In [94]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [95]:
rf = cross_val_score(
    knn,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

_scores = cross_val_score(
    knn,
    X,
    y,
    cv=5,
    scoring="f1_macro"
)

print("Scores de chaque fold :", rf)
print("Moyenne :", rf.mean())
print("Écart-type :", rf.std())

Scores de chaque fold : [0.96658312 0.96658312 0.93265993 0.96658312 1.        ]
Moyenne : 0.9664818612187034
Écart-type : 0.021295160208553578
